### ISSUE TITLE
Investigate building Raspberry Pi version

### ISSUE THREAD

**Issue by lunarcloud** [lunarcloud/rpg-maker-vx-installer-scripts#10]
https://github.com/Ancurio/mkxp/issues/43

**Comment by lunarcloud** [comment]
Maybe use this fork to build it: https://github.com/elizagamedev/mkxp-oneshot

**Comment by lunarcloud** [comment]
Use the depkit, use qmake.

**Comment by lunarcloud** [comment]
Build physfs
Build https://github.com/Ancurio/SDL_sound 
sudo ln -s /usr/local/include/SDL2/SDL_sound.h /usr/local/include/

install anything mkxp's cmake complains about, install ruby 2.5 dev, boost-all-dev etc
cmake -DMRIVERSION=2.5 -DCMAKE_CXX_FLAGS=-std=c++11 . && make
rename mkxp.bin.x86 to mkxp.bin.arm

**Comment by lunarcloud** [comment]
mostly worked! had to convert the audio in the game to mp3, but it works!

**Comment by nru1979** [comment]
Hello,
Any track concerning mkxp-z? 
Legacy mkxp from Ancurio seems not to take in account WIN32 api on which many RGSS1/2/3 are built on.
Thanks!

**Comment by lunarcloud** [comment]
No, and honestly, the ARM build I created crashed because of some texture limit in the pie4 graphics driver. I think it's probably not possible. You're better off switching to rpgmaker MV or an x86 based device (like Steam Deck) if you're using VX and this project.

**Comment by lunarcloud** [comment]
> Hello, Any track concerning mkxp-z? 

I think you mean to comment this on #9 and no. I welcome anyone who wants to contribute a pull request though.

**Comment by nru1979** [comment]
My goal is to make it work to play existing games on RPI so it's a bit on the 2 topics...
I've also tried to compile it first going very slowly with ruby, ruby gems... so far no result.
for MV and MZ, nwjs gives fantastic results on RPI already :-)

**Comment by lunarcloud** [comment]
Ah, well I had a working build, but it crashed at certain points because of a texture size limit in the graphics driver, so I'm not sure the pi4 can really run VX games, sadly, so I abandoned the idea.
