### ISSUE TITLE
About The Last Step of the Instruction

### ISSUE THREAD

**Issue by BlackMages** [lunarcloud/rpg-maker-vx-installer-scripts#3]
Hi! I have some issue regarding the final step of the instruction given. So, I managed to get it to step 7 and finish it. It shows "Finished building".But I dunno what happened after this step. Where the created application goes?

I do realized that there's a .dmg files created. I suspect that this is the launcher for MacOS as they have .dmg extension. How about the linux one?

Thanks! :)

**Comment by lunarcloud** [comment]
The Linux output is *.deb
Hopefully it didn't mess up without telling you. What OS version are you running from?

**Comment by lunarcloud** [comment]
No further feedback has been provided. I'd have loved to help.

**Comment by lunarcloud** [comment]
Issue building was on 
Ubuntu 16.04.5 LTS

This is likely because no mechanism to install all the prerequisites or warn about them missing is currently provided.

**Comment by lunarcloud** [comment]
I can say now that I've tested and made fixes.
This software will run on a new Ubuntu 16.04.5 system if the instructions are followed.
This should be fine using da3d57e91b114c7e862adaf67b0bf344ba707bf7 now
